import type { FFmpeg } from "@ffmpeg/ffmpeg";
import type { LyricLine } from "./lrc";

export interface AppState {
  title: string;
  artist: string;
  coverUrl: string;
  audioUrl: string;
  audioFile: File | null;
  lyrics: LyricLine[];
  originalLyrics: LyricLine[];
  lyricsGlobalOffsetMs: number;
  currentIndex: number;
  recordingMode: boolean;
  panelHidden: boolean;
  objectUrls: string[];
  lastExportUrl: string | null;
  isExporting: boolean;
  isMuxing: boolean;
  mediaRecorder: MediaRecorder | null;
  recordedChunks: Blob[];
  displayStream: MediaStream | null;
  shouldSaveExport: boolean;
  exportBaseName: string;
  exportAudioLeadInMs: number;
  pendingRecordingStartAc: AbortController | null;
  pendingPlaybackStartAc: AbortController | null;
  playbackSyncFrame: number;
  ffmpeg: FFmpeg | null;
  ffmpegLoadPromise: Promise<FFmpeg> | null;
  ffmpegAssetUrls: string[];
  exportJobCount: number;
  exportEndedAc: AbortController | null;
  lyricLineElements: HTMLDivElement[];
  lastProgressPercent: string;
  lastProgressValue: string;
  lastTimeText: string;
  lastDurationText: string;
}

export interface AppElements {
  app: HTMLDivElement;
  audio: HTMLAudioElement;
  exportVideoBtn: HTMLButtonElement;
  exportStatus: HTMLDivElement;
  cover: HTMLImageElement;
  title: HTMLHeadingElement;
  artist: HTMLDivElement;
  lyricsViewport: HTMLDivElement;
  lyricsTrack: HTMLDivElement;
  currentTime: HTMLDivElement;
  duration: HTMLDivElement;
  progress: HTMLInputElement;
  panel: HTMLDialogElement;
  titleInput: HTMLInputElement;
  artistInput: HTMLInputElement;
  lrcInput: HTMLTextAreaElement;
  coverInput: HTMLInputElement;
  audioInput: HTMLInputElement;
  fontScaleInput: HTMLInputElement;
  coverScaleInput: HTMLInputElement;
  playBtn: HTMLButtonElement;
  togglePanelBtn: HTMLButtonElement;
  toggleRecordingBtn: HTMLButtonElement;
  loadDemoBtn: HTMLButtonElement;
  resetViewBtn: HTMLButtonElement;
  shortcutsBadge: HTMLDivElement;
  panelTitle: HTMLDivElement;
  songTitleLabel: HTMLLabelElement;
  artistLabel: HTMLLabelElement;
  coverLabel: HTMLLabelElement;
  coverPickerLabel: HTMLLabelElement;
  audioLabel: HTMLLabelElement;
  audioPickerLabel: HTMLLabelElement;
  lrcLabel: HTMLLabelElement;
  lrcCalibrationLabel: HTMLLabelElement;
  lrcCalibrationHint: HTMLDivElement;
  lrcOffsetLabel: HTMLLabelElement;
  lrcOffsetInput: HTMLInputElement;
  lrcOffsetValue: HTMLDivElement;
  nudgeLrcBackBtn: HTMLButtonElement;
  nudgeLrcForwardBtn: HTMLButtonElement;
  alignCurrentLyricBtn: HTMLButtonElement;
  resetLrcCalibrationBtn: HTMLButtonElement;
  lrcCalibrationStatus: HTMLDivElement;
  fontScaleLabel: HTMLLabelElement;
  coverScaleLabel: HTMLLabelElement;
  bgDarknessInput: HTMLInputElement;
  bgDarknessLabel: HTMLLabelElement;
  bgBlurInput: HTMLInputElement;
  bgBlurLabel: HTMLLabelElement;
  bgAnimateInput: HTMLInputElement;
  bgAnimateLabel: HTMLSpanElement;
  workflowHint: HTMLDivElement;
}

export const FFMPEG_CORE_BASE =
  "https://cdn.jsdelivr.net/npm/@ffmpeg/core@0.12.10/dist/esm";
export const EXPORT_RECORDING_MIME_TYPE = "video/webm;codecs=vp9";
export const EXPORT_START_TIMEOUT_MS = 1200;
